# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P1_Ejemplo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 80, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 230, 47, 13))
        self.label_2.setObjectName("label_2")
        self.txt_numero1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_numero1.setGeometry(QtCore.QRect(210, 90, 113, 20))
        self.txt_numero1.setObjectName("txt_numero1")
        self.txt_numero2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_numero2.setGeometry(QtCore.QRect(190, 230, 113, 20))
        self.txt_numero2.setObjectName("txt_numero2")
        self.btn_suma = QtWidgets.QPushButton(self.centralwidget)
        self.btn_suma.setGeometry(QtCore.QRect(300, 340, 111, 41))
        self.btn_suma.setObjectName("btn_suma")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Numero 1"))
        self.label_2.setText(_translate("MainWindow", "Numero 2"))
        self.btn_suma.setText(_translate("MainWindow", "SUMA"))
